# app.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.instance.name }}-replay-service
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.instance.name }}-replay-service
    instance: {{ .Values.instance.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  serviceName: {{ .Values.instance.name }}-replay-service
  replicas: {{ .Values.transaction_syncing_service.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.instance.name }}-replay-service
      instance: {{ .Values.instance.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.instance.name }}-replay-service
        instance: {{ .Values.instance.name }}
    spec:
      securityContext:
        fsGroup: 1001
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1001:1001 /data"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: state-data
              mountPath: /data
      containers:
        - name: transaction-replay-service
          image: {{ .Values.transaction_syncing_service.image.repository }}:{{ .Values.transaction_syncing_service.image.tag }}
          resources:
            limits:
              cpu: {{ .Values.transaction_syncing_service.resources.limits.cpu }}
              memory: {{ .Values.transaction_syncing_service.resources.limits.memory }}
            requests:
              cpu: {{ .Values.transaction_syncing_service.resources.requests.cpu }}
              memory: {{ .Values.transaction_syncing_service.resources.requests.memory }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ .Values.instance.name }}-replay-service-config
          volumeMounts:
            - name: state-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: state-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.transaction_syncing_service.storage.storageClassName | default "gp2" }}
        resources:
          requests:
            storage: {{ .Values.transaction_syncing_service.storage.size | default "50Mi" }}
