namespace:
  name: default

instance:
  name: paradex-testnet

transaction_syncing_service:
  environment:
    RPC_URL_ORIGINAL_NODE: "https://pathfinder.api.testnet.paradex.trade"
    RPC_URL_SYNCING_NODE: "http://paradex-testnet-madara-service-dev.madara-full-node.svc.cluster.local:9944"
    ADMIN_RPC_URL_SYNCING_NODE: "http://paradex-testnet-madara-service-dev.madara-full-node.svc.cluster.local:9943"
    CLEAN_STATE: "false"
# Deploy paradex-testnet instance
# helm install paradex-testnet-replay ./helm -f ./helm/values-paradex-testnet.yaml
# helm uninstall paradex-testnet-replay
