namespace:
  name: madara-full-node

instance:
  name: paradex-testnet

transaction_syncing_service:
  environment:
    CLEAN_SLATE: "false"
    NODE_ENV: "production"
    DEPLOYMENT_ENVIRONMENT: "production"
    RPC_URL_ORIGINAL_NODE: "https://pathfinder.api.testnet.paradex.trade"
    RPC_URL_SYNCING_NODE: "http://paradex-testnet-madara-service-dev.madara-full-node.svc.cluster.local:9944"
    ADMIN_RPC_URL_SYNCING_NODE: "http://paradex-testnet-madara-service-dev.madara-full-node.svc.cluster.local:9943"
    OTEL_ENABLED: "true"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-collector.otel-stack.svc.cluster.local:4318"
    OTEL_EXPORT_INTERVAL_MS: "3000"
    OTEL_SERVICE_NAME: "paradex-testnet-transaction-replay-service"
# Deploy paradex-testnet instance
# helm install paradex-testnet-replay ./helm -f ./helm/values-paradex-testnet.yaml -n madara-full-node
# helm uninstall paradex-testnet-replay -n madara-full-node
