namespace:
  name: madara-full-node

instance:
  name: paradex-mainnet

transaction_syncing_service:
  environment:
    PORT: "3000"
    CLEAN_SLATE: "false"
    NODE_ENV: "production"
    DEPLOYMENT_ENVIRONMENT: "production"
    RPC_URL_ORIGINAL_NODE: "https://pathfinder.api.prod.paradex.trade"
    RPC_URL_SYNCING_NODE: "http://paradex-mainnet-madara-service.madara-full-node.svc.cluster.local:9944"
    ADMIN_RPC_URL_SYNCING_NODE: "http://paradex-mainnet-madara-service.madara-full-node.svc.cluster.local:9943"
    OTEL_ENABLED: "true"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-collector.otel-stack.svc.cluster.local:4318"
    OTEL_EXPORT_INTERVAL_MS: "3000"
    OTEL_SERVICE_NAME: "paradex-mainnet-transaction-replay-service"
# Deploy paradex-mainnet instance
# helm install paradex-mainnet-replay ./helm -f ./helm/values-paradex-mainnet.yaml -n madara-full-node
# helm uninstall paradex-mainnet-replay
